-- AlterTable
ALTER TABLE "Peserta" ALTER COLUMN "nik" SET DEFAULT LPAD(FLOOR(RANDOM() * 10000000000000000)::TEXT, 16, '0');

-- AlterTable
ALTER TABLE "Token" ADD COLUMN     "role" "Role" NOT NULL DEFAULT 'ADMIN';
