-- CreateEnum
CREATE TYPE "Role" AS ENUM ('ADMIN', 'SMP', 'MPP', 'MMPP', 'IMP', 'PPH', 'ACS');

-- AlterTable
ALTER TABLE "Admin" ADD COLUMN     "role" "Role" NOT NULL DEFAULT 'ADMIN';

-- AlterTable
ALTER TABLE "Peserta" ALTER COLUMN "nik" SET DEFAULT LPAD(FLOOR(RANDOM() * 10000000000000000)::TEXT, 16, '0');
