-- AlterTable
ALTER TABLE "Peserta" ALTER COLUMN "nik" SET DEFAULT LPAD(FLOOR(RANDOM() * 10000000000000000)::TEXT, 16, '0');

-- CreateTable
CREATE TABLE "PapikostickScoring" (
    "id" SERIAL NOT NULL,
    "pesertaId" INTEGER NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "statusSent" INTEGER NOT NULL,
    "sub1" TEXT NOT NULL DEFAULT 'NULL',
    "sub2" TEXT NOT NULL DEFAULT 'NULL',
    "sub3" TEXT NOT NULL DEFAULT 'NULL',
    "sub4" TEXT NOT NULL DEFAULT 'NULL',
    "sub5" TEXT NOT NULL DEFAULT 'NULL',
    "sub6" TEXT NOT NULL DEFAULT 'NULL',
    "sub7" TEXT NOT NULL DEFAULT 'NULL',
    "sub8" TEXT NOT NULL DEFAULT 'NULL',
    "sub9" TEXT NOT NULL DEFAULT 'NULL',
    "sub10" TEXT NOT NULL DEFAULT 'NULL',
    "sub11" TEXT NOT NULL DEFAULT 'NULL',
    "sub12" TEXT NOT NULL DEFAULT 'NULL',
    "sub13" TEXT NOT NULL DEFAULT 'NULL',
    "sub14" TEXT NOT NULL DEFAULT 'NULL',
    "sub15" TEXT NOT NULL DEFAULT 'NULL',
    "sub16" TEXT NOT NULL DEFAULT 'NULL',
    "sub17" TEXT NOT NULL DEFAULT 'NULL',
    "sub18" TEXT NOT NULL DEFAULT 'NULL',
    "sub19" TEXT NOT NULL DEFAULT 'NULL',
    "sub20" TEXT NOT NULL DEFAULT 'NULL',

    CONSTRAINT "PapikostickScoring_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "PapikostickScoring" ADD CONSTRAINT "PapikostickScoring_pesertaId_fkey" FOREIGN KEY ("pesertaId") REFERENCES "Peserta"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
