import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const msdtSeed = async () => {
    const data = [
        { questionIndex: 1, options: ["Saya tidak akan menegur pelanggar-pelanggar peraturan bila saya merasa pasti bahwa tidak ada satu orang pun yang mengetahui tentang pelanggar-pelanggar tersebut.", "Bila saya mengumumkan suatu keputusan yang kurang menyenangkan, saya akan menjelaskan kepada bawahan saya bahwa keputusan ini dibuat oleh direktur."] },
        { questionIndex: 2, options: ["Bila ada seorang karyawan yang hasil kerjanya selalu tidak memuaskan saya, saya akan menunggu suatu kesempatan untuk memindahkannya dan bukan untuk memecatnya.", "Bila ada bawahan saya yang dikucilkan dari kelompok kerjanya, saya akan mencari jalan agar orang lain dapat berteman dengannya."] },
        { questionIndex: 3, options: ["Bila direktur memberikan perintah yang kurang menyenangkan, saya pikir adalah cukup bijaksana bila saya menyebutkan namanya bukan nama saya.", "Bila biasanya membuat keputusan-keputusan sendiri dan menyampaikannya kepada bawahan saya."] },
        { questionIndex: 4, options: ["Bila saya ditegur oleh atasan saya, saya akan memanggil semua bawahan saya dan mengatakan semua teguran tersebut kepada mereka.", "Saya selalu memberikan tugas-tugas yang sangat sulit kepada karyawan-karyawan yang paling berpengalaman."] },
        { questionIndex: 5, options: ["Saya selalu melakukan diskusi-diskusi untuk mencapai kata sepakat.", "Saya selalu menganjurkan kepada bawahan saya untuk memberikan usul-usul, tetapi kadang-kadang saya langsung mengambil tindakan tertentu."] },
        { questionIndex: 6, options: ["Seringkali saya lebih mementingkan tugas daripada diri saya sendiri.", "Saya mengijinkan bawahan-bawahan saya untuk ikut serta dalam mengambil keputusan."] },
        { questionIndex: 7, options: ["Bila jumlah dan mutu hasil kerja bagian saya tidak memuaskan, saya mengatakan kepada bawahan-bawahan saya bahwa direktur merasa kecewa. Oleh karena itu, mereka harus memperbaiki kerja mereka.", "Saya membuat keputusan-keputusan sendiri dan kemudian saya mencoba untuk \"menjual\" keputusan-keputusan itu kepada bawahan saya."] },
        { questionIndex: 8, options: ["Bila saya mengumumkan suatu keputusan yang kurang menyenangkan, saya akan menjelaskan kepada bawahan saya bahwa keputusan ini dibuat oleh direktur.", "Saya mengijinkan bawahan-bawahan saya untuk ikut serta di dalam pengambilan keputusan, tetapi saya pun menyediakan sesuatu yang jitu sebagai keputusan akhir."] },
        { questionIndex: 9, options: ["Saya akan memberikan tugas-tugas yang sulit kepada bawahan saya yang belum berpengalaman, tetapi bila mereka memperoleh kesukaran, saya akan mengambil alih tanggung jawab mereka.", "Bila jumlah dan mutu hasil kerja bagian saya tidak memuaskan, saya menjelaskan kepada bawahan-bawahan saya bahwa direktur merasa kecewa. Oleh karena itu, mereka harus memperbaiki mutu kerja mereka itu."] },
        { questionIndex: 10, options: ["Saya merasa bahwa dengan bekerja keras untuk bawahan saya, mereka akan menyukai saya.", "Saya membiarkan orang lain menangani tugas mereka masing-masing, walaupun mereka membuat banyak kesalahan."] },
        { questionIndex: 11, options: ["Saya menunjukkan minat saya terhadap kehidupan pribadi bawahan-bawahan saya, karena saya pun mengharapkan mereka berbuat seperti itu kepada saya.", "Saya merasa bahwa bawahan-bawahan saya tidak perlu mengerti mengapa mereka mengerjakan sesuatu hal, sejauh mereka mengerjakan hal tersebut."] },
        { questionIndex: 12, options: ["Saya percaya bahwa bawahan-bawahan yang tidak disiplin tidak akan memperbaiki jumlah atau mutu kerja mereka dalam jangka waktu yang panjang.", "Bila menghadapi masalah yang sulit, saya berusaha untuk mencapai pemecahan yang dapat diterima oleh sebagian besar orang."] },
        { questionIndex: 13, options: ["Bila beberapa bawahan saya merasa tidak berbahagia, saya akan mencoba melakukan sesuatu untuk mengatasi hal tersebut.", "Saya berusaha bekerja sebaik mungkin dan memberikan ide-ide pengembangan pada pimpinan."] },
        { questionIndex: 14, options: ["Saya menyetujui kenaikan tunjangan-tunjangan untuk staf dan karyawan.", "Saya mendukung bawahan saya yang ingin meningkatkan pengetahuan tentang pekerjaan dan perusahaan, walaupun hal itu sebenarnya belum diperlukan untuk kedudukan mereka sekarang."] },
        { questionIndex: 15, options: ["Saya membiarkan orang lain menangani tugas mereka masing-masing, walaupun mereka banyak membuat kesalahan.", "Saya membuat keputusan-keputusan sendiri, tetapi saya akan mempertimbangkan usul-usul dari bawahan-bawahan saya."] },
        { questionIndex: 16, options: ["Bila ada bawahan saya yang dikucilkan dari kelompok kerjanya, saya akan mencari cara agar orang lain dapat berteman dengannya.", "Bila seorang karyawan tidak sanggup menyelesaikan tugasnya, saya akan membantu dia untuk menyelesaikan tugas tersebut."] },
        { questionIndex: 17, options: ["Saya percaya bahwa penerapan disiplin merupakan contoh untuk karyawan-karyawan lain.", "Saya merasa saya lebih mementingkan tugas daripada diri saya sendiri."] },
        { questionIndex: 18, options: ["Saya mencela pembicaraan-pembicaraan yang tidak perlu di antara bawahan-bawahan saya, selama mereka bekerja.", "Saya menyetujui kenaikan tunjangan-tunjangan untuk staf dan karyawan."] },
        { questionIndex: 19, options: ["Saya selalu memperhatikan keterlambatan dan kemangkiran bawahan saya.", "Saya percaya bahwa serikat-serikat buruh akan mencoba meruntuhkan kewibawaan pimpinan perusahaan."] },
        { questionIndex: 20, options: ["Kadang-kadang saya merasa bahwa apa yang dikeluhkan oleh serikat buruh bukanlah masalah yang mendasar.", "Saya merasa bahwa keluhan-keluhan tidak dapat dicegah dan saya akan berusaha untuk menghilangkan keluhan tersebut."] },
        { questionIndex: 21, options: ["Adalah penting bagi saya untuk memperoleh penghargaan atas ide-ide saya yang baik.", "Saya mengemukakan pendapat-pendapat saya di muka umum hanya bila saya merasa bahwa orang lain akan setuju dengan saya."] },
        { questionIndex: 22, options: ["Saya percaya bahwa serikat-serikat buruh akan mencoba meruntuhkan kewibawaan pimpinan perusahaan.", "Saya percaya bahwa pertemuan-pertemuan yang sering dengan karyawan secara pribadi akan membantu pengembangan diri mereka."] },
        { questionIndex: 23, options: ["Saya merasa bawahan-bawahan saya tidak perlu mengerti mengapa mereka mengerjakan sesuatu hal sejauh mereka mengerjakan hal tersebut.", "Saya merasa bahwa jam pencatat waktu datang dan pulangnya para pegawai akan mengurangi keterlambatan."] },
        { questionIndex: 24, options: ["Saya biasanya membuat keputusan-keputusan sendiri dan menyampaikannya kepada bawahan saya.", "Saya merasa bahwa serikat-serikat buruh dan pimpinan perusahaan dapat bekerjasama untuk mencapai tujuan-tujuan bersama."] },
        { questionIndex: 25, options: ["Saya menyukai penggunaan skala penggajian karyawan.", "Saya selalu melakukan diskusi-diskusi untuk mencapai kata sepakat."] },
        { questionIndex: 26, options: ["Saya tidak akan memberikan tugas yang tidak saya senangi kepada orang lain.", "Bila beberapa bawahan saya merasa tidak berbahagia, saya akan mencoba melakukan sesuatu untuk mengatasi hal tersebut."] },
        { questionIndex: 27, options: ["Bila ada tugas yang mendesak, walaupun semua peralatannya sudah disediakan, saya akan membiarkannya saja dan meminta salah seorang bawahan saya untuk mengerjakan tugas tersebut.", "Adalah penting bagi saya untuk memperoleh penghargaan atas ide-ide saya yang baik."] },
        { questionIndex: 28, options: ["Tujuan saya adalah berusaha mengerjakan tugas sebaik mungkin tanpa mengeluh.", "Saya memberikan tugas kepada bawahan saya tanpa banyak mempertimbangkan pengalaman atau kemampuan, saya lebih menuntut pencapaian hasilnya saja."] },
        { questionIndex: 29, options: ["Saya memberikan tugas kepada bawahan saya tanpa banyak mempertimbangkan pengalaman atau kemampuan. Saya lebih menuntut pada pencapaian hasilnya saja.", "Saya dengan sabar mendengarkan keluhan-keluhan dan ketidakpuasan bawahan saya, tetapi seringkali saya meralat apa yang mereka katakan."] },
        { questionIndex: 30, options: ["Saya merasa bahwa keluhan-keluhan tidak dapat dicegah dan saya berusaha untuk menghilangkan keluhan tersebut.", "Saya percaya bahwa bawahan-bawahan saya akan merasakan kepuasan kerja tanpa merasa tertekan oleh saya."] },
        { questionIndex: 31, options: ["Bila menghadapi masalah yang sulit, saya berusaha untuk mencapai pemecahan yang dapat diterima oleh sebagian besar orang.", "Saya percaya bahwa pengalaman bekerja lebih bermanfaat daripada pendidikan teoritis."] },
        { questionIndex: 32, options: ["Saya selalu memberikan tugas-tugas yang sangat sulit kepada karyawan-karyawan yang paling berpengalaman.", "Saya percaya bahwa kenaikan jabatan adalah semata-mata berdasarkan kemampuan yang ada."] },
        { questionIndex: 33, options: ["Saya merasa bahwa masalah-masalah yang timbul di antara para karyawan-karyawan biasanya akan dapat diselesaikan di antara mereka sendiri, tanpa campur tangan dari saya.", "Bila saya ditegur oleh atasan saya, saya akan memanggil semua bawahan saya dan mengatakan semua teguran tersebut kepada mereka."] },
        { questionIndex: 34, options: ["Saya tidak peduli dengan apa yang dikerjakan oleh karyawan saya diluar jam kerja kantornya.", "Saya percaya bahwa bawahan-bawahan yang tidak disiplin tidak akan memperbaiki jumlah atau mutu kerja mereka dalam jangka waktu yang panjang."] },
        { questionIndex: 35, options: ["Saya akan memberikan informasi kepada pimpinan perusahaan tidak lebih dari apa yang mereka tanyakan.", "Kadang-kadang saya merasa bahwa apa yang dikeluhkan oleh serikat buruh bukanlah masalah yang mendasar."] },
        { questionIndex: 36, options: ["Saya kadang ragu-ragu untuk membuat suatu keputusan yang akan tidak disukai oleh bawahan-bawahan saya.", "Tujuan saya adalah berusaha mengerjakan tugas sebaik mungkin tanpa mengeluh."] },
        { questionIndex: 37, options: ["Saya dengan sabar mendengarkan keluhan-keluhan dan ketidakpuasan-ketidakpuasan dari bawahan saya, tetapi seringkali meralat apa yang mereka katakan.", "Saya kadang ragu-ragu untuk membuat suatu keputusan yang akan tidak disukai oleh bawahan-bawahan saya."] },
        { questionIndex: 38, options: ["Saya mengemukakan pendapat-pendapat saya dimuka umum hanya bila saya merasa bahwa orang ain akan setuju dengan saya.", "Sebagian besar dari bawahan-bawahan saya dapat menyelesaikan tugas-tugas mereka, bila perlu tanpa kehadiran saya."] },
        { questionIndex: 39, options: ["Saya berusaha bekerja sebaik mungkin dan memberikan ide-ide pengembangan pada pimpinan perusahaan.", "Bila saya memberikan tugas kepada bawahan-bawahan saya, saya menentukan batas penyelesaiannya."] },
        { questionIndex: 40, options: ["Saya selalu menganjurkan kepada bawahan-bawahan saya untuk memberikan usul-usul, tetapi kadang-kadang saya langsung mengambil tindakan tertentu.", "Saya mencoba membuat bawahan-bawahan saya merasa senang apabila mereka berbicara dengan saya."] },
        { questionIndex: 41, options: ["Di dalam diskusi-diskusi saya memberikan fakta-fakta sesuai pemahaman saya, dan membiarkan mereka untuk membuat kesimpulan sendiri.", "Bila direktur memberikan perintah yang kurang menyenangkan, saya pikir saya cukup bijaksana bila saya menyebutkan namanya, bukan nama saya."] },
        { questionIndex: 42, options: ["Bila ada tugas-tugas mendadak atau tugas yang tidak menyenangkan, sebelumnya saya akan meminta beberapa sukarelawan untuk mengerjakan tugas-tugas tersebut.", "Saya menunjukkan minat saya terhadap kehidupan pribadi bawahan-bawahan saya karena saya pun mengharapkan mereka berbuat seperti itu pada saya."] },
        { questionIndex: 43, options: ["Saya selalu memperhatikan kebahagiaan karyawan-karyawan saya saat mereka mengerjakan tugas-tugas mereka.", "Saya selalu memperhatikan keterlambatan dan kemangkiran bawahan saya."] },
        { questionIndex: 44, options: ["Sebagian besar dari bawahan-bawahan saya dapat menyelesaikan tugas-tugas mereka, bila perlu tanpa kehadiran saya.", "Bila ada sesuatu tugas yang mendesak, walaupun semua peralatannya sudah disiapkan, saya akan membiarkannya saja dan meminta salah seorang bawahan saya untuk mengerjakan tugas tersebut."] },
        { questionIndex: 45, options: ["Saya percaya bahwa bawahan-bawahan saya akan merasakan kepuasan kerja tanpa merasa tertekan oleh saya.", "Saya memberikan informasi kepada \"Dewan Pimpinan Perusahaan\" tidak lebih dari apa yang mereka katakan."] },
        { questionIndex: 46, options: ["Saya percaya bahwa pertemuan-pertemuan yang sering dengan karyawan secara pribadi akan membantu pengembangan diri mereka.", "Saya selalu memperhatikan kebahagiaan karyawan-karyawan saya saat mereka mengerjakan tugas-tugas mereka."] },
        { questionIndex: 47, options: ["Saya mendukung bawahan saya yang ingin meningkatkan pengetahuan tentang pekerjaan dan perusahaan, walaupun hal itu sebenarnya belum diperlukan untuk kedudukan mereka sekarang.", "Saya mengawasi benar bawahan-bawahan saya yang kurang mahir dalam pekerjaannya atau bawahan-bawahan saya yang hasil kerjanya kurang memuaskan."] },
        { questionIndex: 48, options: ["Saya mengijinkan bawahan-bawahan saya untuk ikut serta dalam mengambil keputusan dan saya selalu mematuhi keputusan yang dibuat berdasarkan suara terbanyak.", "Saya membuat bawahan-bawahan saya bekerja keras, dan saya berusaha meyakinkan mereka bahwa biasanya mereka akan mendapatkan perlakuan yang adil dari pimpinan perusahaan."] },
        { questionIndex: 49, options: ["Saya merasa bahwa semua karyawan pada jabatan yang sama seharusnya memperoleh gaji yang sama.", "Bila ada seorang karyawan yang hasil kerjanya selalu tidak memuaskan saya, saya akan menunggu suatu kesempatan untuk memindahkannya, dan bukan untuk memecatnya."] },
        { questionIndex: 50, options: ["Saya merasa bahwa tujuan-tujuan serikat buruh dan tujuan-tujuan perusahaan saling berbeda.", "Saya merasa bahwa dengan bekerja keras bagi bawahan saya, mereka akan menyenangi saya."] },
        { questionIndex: 51, options: ["Saya mengawasi benar bawahan-bawahan saya yang kurang mahir dalam pekerjaannya atau bawahan-bawahan saya yang hasil kerjanya kurang memuaskan.", "Saya mencela pembicaraan-pembicaraan yang tidak perlu diantara bawahan-bawahan saya, selama mereka bekerja."] },
        { questionIndex: 52, options: ["Bila saya memberi tugas kepada bawahan-bawahan saya, saya menentukan batas waktu penyelesaiannya.", "Saya tidak akan memberikan tugas yang tidak saya senangi kepada orang lain."] },
        { questionIndex: 53, options: ["Saya percaya bahwa pengalaman bekerja lebih bermanfaat daripada pendidikan teoritis.", "Saya tidak peduli dengan apa yang dikerjakan oleh para pegawai saya diluar jam kantornya."] },
        { questionIndex: 54, options: ["Saya merasa bahwa jam pencatat waktu datang dan pulangnya para pegawai akan mengurangi keterlambatan.", "Saya mengijinkan bawahan-bawahan saya untuk ikut serta dalam pengambilan keputusan dan saya selalu mematuhi keputusan yang dibuat berdasarkan suara terbanyak."] },
        { questionIndex: 55, options: ["Saya membuat keputusan-keputusan sendiri, tetapi saya dapat mempertimbangkan saran-saran yang wajar dari bawahan-bawahan saya.", "Saya merasa bahwa tujuan-tujuan serikat buruh dan tujuan-tujuan perusahaan adalah saling berbeda."] },
        { questionIndex: 56, options: ["Saya membuat keputusan-keputusan sendiri dan kemudian saya mencoba untuk \"menjual\" keputusan-keputusan itu kepada bawahan saya.", "Apabila mungkin, saya akan membentuk kelompok-kelompok kerja yang terdiri dari orang-orang yang sudah menjadi teman-teman baik saya."] },
        { questionIndex: 57, options: ["Saya tidak akan ragu-ragu untuk mempekerjakan pegawai-pegawai yang cacat jasmani, bilamana saya merasa pasti bahwa mereka dapat menangani pekerjaannya.", "Saya tidak akan menegur pelanggar-pelanggar peraturan, bila saya merasa pasti bahwa tidak ada satu orangpun yang mengetahui tentang pelanggaran-pelanggaran tersebut."] },
        { questionIndex: 58, options: ["Apabila mungkin, saya akan membentuk kelompok-kelompok kerja yang terdiri dari orang-orang yang sudah menjadi teman-teman baik saya.", "Saya akan memberikan tugas yang sulit kepada bawahan-bawahan saya yang belum berpengalaman, tetapi bila mereka memperoleh kesukaran, saya akan mengambil alih tanggung jawab mereka."] },
        { questionIndex: 59, options: ["Saya membuat bawahan-bawahan saya bekerja keras dan saya berusaha meyakinkan mereka bahwa biasanya mereka akan mendapat perlakuan yang adil dari pimpinan perusahaan.", "Saya percaya bahwa penerapan disiplin adalah merupakan contoh untuk karyawan-karyawan lainnya."] },
        { questionIndex: 60, options: ["Saya mencoba untuk membuat bawahan-bawahan saya merasa senang apabila mereka berbicara dengan saya.", "Saya menyukai penggunaan skala penggajian karyawan."] },
        { questionIndex: 61, options: ["Saya percaya bahwa kenaikan jabatan adalah semata-mata berdasarkan kemampuan yang ada.", "Saya merasa bahwa masalah-masalah yang timbul diantara para karyawan biasanya akan dapat diselesaikan diantara mereka sendiri tanpa campur tangan dari saya."] },
        { questionIndex: 62, options: ["Saya merasa bahwa serikat-serikat buruh dan pimpinan perusahaan bekerja untuk mencapai tujuan-tujuan yang sama.", "Di dalam diskusi, saya memberikan fakta-fakta sesuai dengan pemahaman bawahan saya dan membiarkan mereka untuk membuat kesimpulan sendiri."] },
        { questionIndex: 63, options: ["Bila seorang karyawan tidak sanggup menyelesaikan tugasnya, saya akan membantu dia untuk menyelesaikan tugas tersebut.", "Saya merasa bahwa semua karyawan pada jabatan yang sama seharusnya memperoleh gaji yang sama."] },
        { questionIndex: 64, options: ["Saya mengijinkan bawahan-bawahan saya untuk ikut serta dalam pengambilan keputusan, tetapi saya pun menyediakan sesuatu yang jitu sebagai keputusan akhir.", "Saya tidak akan ragu-ragu untuk mempekerjakan pegawai-pegawai yang cacat jasmaninya, bilamana saya merasa bahwa mereka dapat menangani pekerjaannya."] }
    ];

  for (const item of data) {
    await prisma.msdtQuestion.create({
      data: {
        questionIndex: item.questionIndex,
        option: {
          create: item.options.map((sentence, index) => ({
            sentences: sentence,
            optionType: index + 1
          }))
        }
      }
    });
  }
};

export { msdtSeed }